### Get all exams
GET http://localhost:3000/api/exams
Content-Type: application/json

###

### Create a new exam
POST http://localhost:3000/api/exams
Content-Type: application/json

{
  "examBoard": "Edexcel",
  "examSubject": "Maths",
  "examComponent": "Paper 2",
  "ExamDate": "2025-06-05",
  "SubjectId": "7bb67e80-5458-444c-a971-8d51678dd3d6",
  "Stacks": ["5caeb689-43e0-469a-9413-74b71dd9334e", "d69dce4b-e310-4793-b564-c2484cd158f8"]
}
###
### Link stack to exam
PUT http://localhost:3000/api/exams/5b1cb541-710a-46bc-bfc1-49396221c326/8c3a8ee6-702a-44ae-abf8-8d84f39de8b0
Content-Type: application/json

###

### Unlink stack from exam
DELETE http://localhost:3000/api/exams/5b1cb541-710a-46bc-bfc1-49396221c326/id-2

### Get a specific exam by UUID
### Update exam by UUID
PUT http://localhost:3000/api/exams/5b1cb541-710a-46bc-bfc1-49396221c326
Content-Type: application/json

{
  "examSubject": "Updated Biology",
  "examComponent": "Updated Paper 1",
  "examBoard": "AQA"
}

### Delete exam by UUID
DELETE http://localhost:3000/api/exams/6cd7f205-b50f-4c0a-b11c-0f1804658d6c