GET http://localhost:3000/api/subject
###
POST http://localhost:3000/api/subject
Content-Type: application/json

{
    "name": "Maths"
}
###
GET http://localhost:3000/api/subject/5f8d40f4-bbb8-4712-8cd5-cd74fe06431b
Content-Type: application/json


###
PUT http://localhost:3000/api/subject/14ccaa40-984b-422f-9a77-8e3d4cddd906
Content-Type: application/json

{
    "name": "Business",
    "description":""
}
###
DELETE http://localhost:3000/api/subject/14ccaa40-984b-422f-9a77-8e3d4cddd906
Content-Type: application/json

